server:
  port: ':8888'
  read_timeout: '30s'
  write_timeout: '30s'
  idle_timeout: '30s'

database:
  url: 'postgres://postgres:postgres@localhost:5432/Nutrition?sslmode=disable'
  open_conns: 10
  idle_conns: 10
  conn_lifetime: '0s'
